package com.card_saver.service.impl;

import com.card_saver.model.User;
import com.card_saver.repository.UserRepository;
import com.card_saver.service.IUserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Handles services that results in/require users.
 */
@Service
public class UserServiceImpl implements IUserService {

    @Autowired
    UserRepository userRepository;

    /**
     * Checks whether the User (username/password combination) is contained in the database.
     * If the User already exists, it fetches the User's id from the database, sets it onto
     * the parameter User's id and returns it.
     * If the User does not exist, it checks whether the username is already in use.
     * If the username is already in use it sets the parameter User's id to -1 and returns it.
     * If the username is not already in use,
     * it creates a new user and sets it's id to the one generated by the database.
     * @param user - The user object that was created by the login form.
     * @return - The user object, now with a set id.
     */
    @Override
    public User handleLogin(User user) {
        if(userRepository.userExists(user)){
            user.setId(userRepository.getUserId(user));

        } else {
            if(userRepository.usernameIsUnique(user)){
                userRepository.createUser(user);

            } else {
                user.setId(-1);
            }
        }
        return user;
    }
}
