package com.card_saver.service.impl;

import com.card_saver.model.User;
import com.card_saver.repository.UserRepository;
import com.card_saver.service.IUserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/**
 * Handles services that results in/require users.
 */
@Service
public class UserServiceImpl implements IUserService {

    @Autowired
    UserRepository userRepository;

    /**
     * Checks whether the user (or login) is contained in the database.
     * If the user is contained, it fetches the users id from the database. If the user is not contained,
     * it creates a new user and sets its ID to the one generated by the database.
     * @param user - The user object that was created by the login form.
     * @return - The user object, now with set ID.
     */
    @Override
    public User handleLogin(User user) {
        if(userRepository.validateUserExists(user)){
            user.setId(userRepository.getUserId(user));
        } else {
            userRepository.createUser(user);
        }
        return user;
    }
}
